# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6-0Qp3oiBh4fKOXJpRNHtLlYn75qKtj
"""

curso = 'Ensino a Distancia'
curso

#Código para letras maiusculas
curso.upper()

#Código para letras minusculas
curso.lower()

#Código para quebra de substrings
curso.split()